### PR TITLE
form and ui component overhaul

### PR DESCRIPTION
**Pull request by jsun-1**
Hey @khanhtruong0808, I made changes to the UI components to use `shadcn/ui` and then customized them a bit. Note that for customizing colors, the website is currently in dark mode only at the `html` tag level, so if you want to customize color for one of the ui components, then prefix it with `dark` like `dark:text-red-600`.

I made this change in part because shadcn has form components that are already integrated with React Hook Form so it saves a little bit of effort in setting up the forms. Also, React Hook Form made it a lot easier to implement the local storage form saving that Josh suggested.

Please check out `src/components/forms/UpdateProductionForm.tsx` and `useFormWithLocalStorage` in `src/lib/hooks.ts` to see how the local storage form is implemented. Could you please help me convert the rest of the forms to use the RHF/shadcn components like this?

### CODE REVIEW

**Comment by khanhtruong0808** [comment]
> Hey @khanhtruong0808, I made changes to the UI components to use `shadcn/ui` and then customized them a bit. Note that for customizing colors, the website is currently in dark mode only at the `html` tag level, so if you want to customize color for one of the ui components, then prefix it with `dark` like `dark:text-red-600`.
> 
> I made this change in part because shadcn has form components that are already integrated with React Hook Form so it saves a little bit of effort in setting up the forms. Also, React Hook Form made it a lot easier to implement the local storage form saving that Josh suggested.
> 
> Please check out `src/components/forms/UpdateProductionForm.tsx` and `useFormWithLocalStorage` in `src/lib/hooks.ts` to see how the local storage form is implemented. Could you please help me convert the rest of the forms to use the RHF/shadcn components like this?

Hey @jsun-1, yeah I'll start converting the rest of the forms today

**Comment by khanhtruong0808** [comment]
Hey @jsun-1, I tried to implement the logic to the theater and stage forms and mostly got it working, but I ran into a few problems that I'll try to figure out tomorrow if I can. I'll push these changes just in case you'd like to take a look.

The main things I noticed were that: 
- If you make changes in one form, go somewhere else, and go back, pressing cancel doesn't change the form `isFormDirty` state (the cancel button and warning message still appear after hitting cancel)
- When submitting changes to boolean selects (like wheelchair accessible?), the form would keep the dirty state too. I noticed a work around was to hit save, cancel, and then reload, so it might be something about the field value 
- The same issue above happens for numerical inputs (postal code, seating capacity, etc)
- The Playwrights, Directors, and Composers field break when trying to make changes

Other than that I noticed that the `LOCAL_STORAGE_KEY` being set to `update-production-form` would overlap changes to other productions, so I added the production id to the key. I also noticed that the poster url didn't revert itself when hitting cancel so I think I fixed that too.

**Comment by jsun-1** [comment]
Hey @khanhtruong0808 thanks for noticing those problems and making those changes.

I think my last commit fixed more bugs than it created.

- `isFormDirty` not being reset after hitting cancel should be fixed after extending the form's default `.reset()` method to also clear the local storage
- Boolean selects should be fixed
- Numerical inputs should be fixed
- the array fields like playwrights/directors should be fixed

I also implemented the address lookup for the forms and did some basic datalists for the `title` and `playwrights` fields.

There are probably still bugs and janky stuff so if you test and notice any please let me know

**Comment by khanhtruong0808** [comment]
@jsun-1 I found a few more bugs that I was able to fix by copying your changes, but there were two that looked a bit tricky that I couldn't get to yet:

- Editing "Stage" in the Update Production Form
- Editing the poster in the Update Production Form

Both of the above have similar issues with local storage not updating properly

**Pull request merged**
